# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baml/cffi/v1/baml_object_methods.proto

require 'google/protobuf'

require 'baml/cffi/v1/baml_inbound_pb'
require 'baml/cffi/v1/baml_object_pb'
require 'baml/cffi/v1/baml_outbound_pb'


descriptor_data = "\n&baml/cffi/v1/baml_object_methods.proto\x12\x0c\x62\x61ml.cffi.v1\x1a\x1f\x62\x61ml/cffi/v1/baml_inbound.proto\x1a\x1e\x62\x61ml/cffi/v1/baml_object.proto\x1a baml/cffi/v1/baml_outbound.proto\"\x8d\x01\n\x1a\x42\x61mlObjectMethodInvocation\x12.\n\x06object\x18\x01 \x01(\x0b\x32\x1e.baml.cffi.v1.BamlObjectHandle\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12*\n\x06kwargs\x18\x03 \x03(\x0b\x32\x1a.baml.cffi.v1.HostMapEntry\"y\n\x1f\x42\x61mlObjectConstructorInvocation\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.baml.cffi.v1.BamlObjectType\x12*\n\x06kwargs\x18\x02 \x03(\x0b\x32\x1a.baml.cffi.v1.HostMapEntry\"\xc2\x01\n\x19InvocationResponseSuccess\x12\x30\n\x06object\x18\x01 \x01(\x0b\x32\x1e.baml.cffi.v1.BamlObjectHandleH\x00\x12\x39\n\x07objects\x18\x02 \x01(\x0b\x32&.baml.cffi.v1.RepeatedBamlObjectHandleH\x00\x12.\n\x05value\x18\x03 \x01(\x0b\x32\x1d.baml.cffi.v1.CFFIValueHolderH\x00\x42\x08\n\x06result\"K\n\x18RepeatedBamlObjectHandle\x12/\n\x07objects\x18\x01 \x03(\x0b\x32\x1e.baml.cffi.v1.BamlObjectHandle\"m\n\x12InvocationResponse\x12:\n\x07success\x18\x01 \x01(\x0b\x32\'.baml.cffi.v1.InvocationResponseSuccessH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\n\n\x08responseB\x08Z\x06./cffib\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Baml
  module Cffi
    module V1
      BamlObjectMethodInvocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("baml.cffi.v1.BamlObjectMethodInvocation").msgclass
      BamlObjectConstructorInvocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("baml.cffi.v1.BamlObjectConstructorInvocation").msgclass
      InvocationResponseSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("baml.cffi.v1.InvocationResponseSuccess").msgclass
      RepeatedBamlObjectHandle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("baml.cffi.v1.RepeatedBamlObjectHandle").msgclass
      InvocationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("baml.cffi.v1.InvocationResponse").msgclass
    end
  end
end
