require "bundler/gem_tasks"
require "rake/testtask"

GEMSPEC_PATH = "baml.gemspec"
GEMSPEC = Gem::Specification.load(GEMSPEC_PATH) || abort("Could not load #{GEMSPEC_PATH}")

task default: :test

Rake::TestTask.new do |t|
  t.libs << "lib"
  t.libs << "test"
  t.test_files = FileList["test/*_test.rb"]
end
