# typed: strict
# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ gem install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.
# gem install baml
require "sorbet-runtime"
require "baml"

module BamlClient


  class TypeBuilder
        extend T::Sig

        sig { void }
        def initialize
            @registry = T.let(BamlClient::Internal::DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOU_RE_DOING_RUNTIME.new_type_builder, Baml::Ffi::TypeBuilder)
            @classes = T.let(Set["Example", "Example2"], T::Set[String])
            @enums = T.let(Set[], T::Set[String])
        end

        sig { returns(Baml::Ffi::TypeBuilder) }
        def _registry
            @registry
        end

        sig { returns(Baml::Ffi::FieldType) }
        def string
            @registry.string
        end

        sig { returns(Baml::Ffi::FieldType) }
        def int
            @registry.int
        end

        sig { returns(Baml::Ffi::FieldType) }
        def float
            @registry.float
        end

        sig { returns(Baml::Ffi::FieldType) }
        def bool
            @registry.bool
        end

        sig { params(inner_type: Baml::Ffi::FieldType).returns(Baml::Ffi::FieldType) }
        def list(inner_type)
            @registry.list(inner_type)
        end

        sig { returns(Baml::Ffi::FieldType) }
        def null
            @registry.null
        end

        sig { params(key_type: Baml::Ffi::FieldType, value_type: Baml::Ffi::FieldType).returns(Baml::Ffi::FieldType) }
        def map(key_type, value_type)
            @registry.map(key_type, value_type)
        end

        sig { params(types: T::Array[Baml::Ffi::FieldType]).returns(Baml::Ffi::FieldType) }
        def union(types)
            @registry.union(types)
        end

        sig { params(name: String).returns(ClassBuilder) }
        def add_class(name)
            if @classes.include?(name)
                raise "Class with name #{name} already exists."
            end
            if @enums.include?(name)
                raise "Enum with name #{name} already exists."
            end
            @classes.add(name)
            ClassBuilder.new(@registry.add_class(name))
        end

        sig { params(name: String).returns(EnumBuilder) }
        def add_enum(name)
            if @classes.include?(name)
                raise "Class with name #{name} already exists."
            end
            if @enums.include?(name)
                raise "Enum with name #{name} already exists."
            end
            @enums.add(name)
            EnumBuilder.new(@registry.add_enum(name))
        end

        sig { params(baml: String).void }
        def add_baml(baml)
            @registry.add_baml(baml)
        end

        class ClassBuilder
            extend T::Sig

            sig { params(builder: Baml::Ffi::ClassBuilder, properties: T.nilable(T::Set[String])).void }
            def initialize(builder, properties = nil)
                @builder = T.let(builder, Baml::Ffi::ClassBuilder)
                @properties = T.let(properties == nil ? Set.new : properties, T::Set[String])
            end

            sig { returns(Baml::Ffi::FieldType) }
            def type
                @builder.field
            end

            sig { params(name: String, type: Baml::Ffi::FieldType).returns(Baml::Ffi::ClassPropertyBuilder) }
            def add_property(name, type)
                if @properties.include?(name)
                    raise "Property #{name} already exists."
                end
                @properties.add(name)
                @builder.add_property(name, type)
            end

            sig { returns(T::Array[String]) }
            def list_properties
                @builder.list_properties
            end
        end

        class EnumBuilder
            extend T::Sig

            sig { params(builder: Baml::Ffi::EnumBuilder, values: T.nilable(T::Set[String])).void }
            def initialize(builder, values = nil)
                @builder = T.let(builder, Baml::Ffi::EnumBuilder)
                @values = T.let(values == nil ? Set.new : values, T::Set[String])
            end

            sig { returns(Baml::Ffi::FieldType) }
            def type
                @builder.field
            end

            sig { params(name: String).returns(Baml::Ffi::EnumValueBuilder) }
            def add_value(name)
                if @values.include?(name)
                    raise "Value #{name} already exists."
                end
                @values.add(name)
                @builder.add_value(name)
            end
        end


      def DummyOutput
          ClassBuilder.new(@registry.class_("DummyOutput"), Set[ "nonce",  "nonce2", ])
      end

      def DynInputOutput
          ClassBuilder.new(@registry.class_("DynInputOutput"), Set[ "testKey", ])
      end

      def DynamicClassOne
          ClassBuilder.new(@registry.class_("DynamicClassOne"), Set[])
      end

      def SomeClassNestedDynamic
          ClassBuilder.new(@registry.class_("SomeClassNestedDynamic"), Set[ "hi", ])
      end

      def DynamicClassTwo
          ClassBuilder.new(@registry.class_("DynamicClassTwo"), Set[ "hi",  "some_class",  "status", ])
      end

      def DynamicOutput
          ClassBuilder.new(@registry.class_("DynamicOutput"), Set[])
      end

      def DynamicSchema
          ClassBuilder.new(@registry.class_("DynamicSchema"), Set[])
      end

      def OriginalB
          ClassBuilder.new(@registry.class_("OriginalB"), Set[ "value", ])
      end

      def Person
          ClassBuilder.new(@registry.class_("Person"), Set[ "name",  "hair_color", ])
      end

      def RenderEnumInput
          ClassBuilder.new(@registry.class_("RenderEnumInput"), Set[ "testKey", ])
      end

      def RenderTestClass
          ClassBuilder.new(@registry.class_("RenderTestClass"), Set[ "name",  "status", ])
      end

      def SkipDynamicClass
          ClassBuilder.new(@registry.class_("SkipDynamicClass"), Set[ "value",  "internal_id", ])
      end



      def Color
          EnumBuilder.new(@registry.enum_("Color"), Set[ "RED",  "BLUE",  "GREEN",  "YELLOW",  "BLACK",  "WHITE", ])
      end

      def DynEnumOne
          EnumBuilder.new(@registry.enum_("DynEnumOne"), Set[])
      end

      def DynEnumThree
          EnumBuilder.new(@registry.enum_("DynEnumThree"), Set[ "TRICYCLE",  "TRIANGLE", ])
      end

      def DynEnumTwo
          EnumBuilder.new(@registry.enum_("DynEnumTwo"), Set[])
      end

      def Hobby
          EnumBuilder.new(@registry.enum_("Hobby"), Set[ "SPORTS",  "MUSIC",  "READING", ])
      end

      def RenderStatusEnum
          EnumBuilder.new(@registry.enum_("RenderStatusEnum"), Set[ "ACTIVE",  "INACTIVE", ])
      end

      def RenderTestEnum
          EnumBuilder.new(@registry.enum_("RenderTestEnum"), Set[ "BIKE",  "SCOOTER", ])
      end

  end

end
